---
- hosts: all
  become: yes
  tasks:
    - name: Define the NCLU filename as variable called nclu_file
      set_fact: nclu_file="save_nclu/{{inventory_hostname}}_nclu"

    - name: Load-in the NCLU File as variable called nclu_content
      set_fact: nclu_content="{{ lookup('file', nclu_file) | regex_replace('^net ') | regex_replace('\nnet ','\n') }}"

    - name: Apply the NCLU Commands
      nclu:
        template: "{{nclu_content}}"

    - name: commit the changes
      nclu:
        commit: yes
      # we commit in a separate stanza so we don't have to "per line" in the stanza above
