---
- hosts: all
  become: yes
  tasks:
    - name: run the net commands
      nclu:
        commands:
          - '{{item[4:]}}'
      with_lines: cat save_nclu/{{inventory_hostname}}_nclu
      # with_lines loops through each line in the file, and item[4:] strips off the 'net' in front since its redundant with nclu ansible module
    
    - name: commit the changes
      nclu:
        commit: yes
      # we commit in a separate stanza so we don't have to "per line" in the stanza above  
      
# AUTHOR: Sean Cavanaugh
# EMAIL: sean@cavanaugh.pro
# WORK_EMAIL: sean@cumulusnetworks.com
      
